version: '3.8'

volumes:
  postgres-data:

services:
  database:
    image: postgres:15.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 55432:5432
